version: '3.5'
services:

  # POSTGRESQL CONTAINER
  order-db:
    image: postgres:11-alpine
    ports:
    - '28183:5432'
    container_name: LPDM-OrderDB
    environment:
      POSTGRES_DB: lpdm-order
      POSTGRES_USER: lpdm
      POSTGRES_PASSWORD: lpdm
    volumes:
    - data:/var/lib/postgresql/data
    restart: always
    network_mode: bridge

# DATA VOLUME
volumes:
  data: {}