version: '3.5'
services:

  # POSTGRESQL CONTAINER
  order-db:
    image: postgres:alpine
    ports:
    - '28183:5432'
    container_name: LPDM-OrderDB
    environment:
      POSTGRES_DB: lpdm-order
      POSTGRES_USER: lpdm
      POSTGRES_PASSWORD: lpdm
    volumes:
    - './sql:/docker-entrypoint-initdb.d'
    restart: always
    network_mode: bridge

  # MICROSERVICE CONTAINER
  order-ms:
    container_name: LPDM-OrderMS
    build:
      context: .
      dockerfile: Dockerfile
    external_links:
      - LPDM-OrderDB
    ports:
      - '28083:28083'
    restart: always